---
from_prj: openSUSE:Leap:15.0
project_preference_order:
- SUSE:SLE-15:GA
- openSUSE:Leap:15.0:SLE-workarounds
- openSUSE:Factory
- openSUSE:Factory:NonFree
drop_if_vanished_from:
- SUSE:SLE-15:GA
- openSUSE:Factory
- openSUSE:Factory:NonFree
