---
factory: openSUSE.org:openSUSE:Factory
from_prj: SUSE:SLE-15-SP1:GA
project_preference_order:
- openSUSE.org:openSUSE:Factory
- openSUSE.org:openSUSE:Factory:NonFree
#- openSUSE.org:openSUSE:Leap:15.0:SLE-workarounds
#- openSUSE.org:openSUSE:Leap:15.0
#- openSUSE.org:openSUSE:Leap:15.0:NonFree

