env:
  global:
    - OBS_PACKAGE="home:jberry:travis/openSUSE-release-tools"
    - OBS_USER="jberry"
    # OBS_PASS
    - secure: "0MI2ZbJ+C1FoOa+rBYq3+NQBoQzE528B1mNacZx5xaH6IipFklW9TlCUSO91Pgf2l72HzNL5GhBbYGtAO9og0tyJO9Vm+7F+AUNQHQjfD46r1MyxBlACi6FGwuR+E32OIFilekJCnNKp55Cl5O2wGWUcRRVlM6/+k24dt3lkIoY="

matrix:
  include:
    - env: TEST_SUITE=distribution
      sudo: required
      services:
        - docker
      language: bash
      before_install:
        - docker build -f dist/ci/Dockerfile -t spec .
      script:
        - docker run -it spec ./dist/ci/spec.sh
    - env: TEST_SUITE=nosetests
      sudo: false
      language: python
      python: 2.7
      install:
        # needed to install osc from git in requirements.txt
        - pip install pycurl urlgrabber
        - pip install -r requirements.txt
        - pip install python-coveralls
      script:
        - nosetests --with-coverage --cover-package=osclib --cover-inclusive
      after_success:
        - coveralls

deploy:
  provider: script
  script: docker run -it -e OBS_PACKAGE="$OBS_PACKAGE" -e OBS_USER="$OBS_USER" -e OBS_PASS="$OBS_PASS" spec ./dist/ci/deploy.obs.sh
  on:
    branch: master
    condition: $TEST_SUITE = distribution
