env:
  global:
    - OBS_PACKAGE="openSUSE:Tools/openSUSE-release-tools"
    - OBS_USER="jberry"
    # OBS_PASS
    - secure: "0MI2ZbJ+C1FoOa+rBYq3+NQBoQzE528B1mNacZx5xaH6IipFklW9TlCUSO91Pgf2l72HzNL5GhBbYGtAO9og0tyJO9Vm+7F+AUNQHQjfD46r1MyxBlACi6FGwuR+E32OIFilekJCnNKp55Cl5O2wGWUcRRVlM6/+k24dt3lkIoY="
    - OBS_EMAIL="opensuse-releaseteam@opensuse.org"

matrix:
  include:
    - env: TEST_SUITE=distribution TARGET_REPO=openSUSE_Factory
      sudo: required
      services:
        - docker
      language: bash
      before_install:
        - docker build -f dist/ci/Dockerfile -t spec .
      script:
        - ./dist/ci/docker-run obs-build-target "$TARGET_REPO"
    - env: TEST_SUITE=distribution TARGET_REPO=openSUSE_42.3
      sudo: required
      services:
        - docker
      language: bash
      before_install:
        - docker build -f dist/ci/Dockerfile -t spec .
      script:
        - ./dist/ci/docker-run obs-build-target "$TARGET_REPO"
    - env: TEST_SUITE=distribution TARGET_REPO=SLE_12_SP3
      sudo: required
      services:
        - docker
      language: bash
      before_install:
        - docker build -f dist/ci/Dockerfile -t spec .
      script:
        - ./dist/ci/docker-run obs-build-target "$TARGET_REPO"
    - env: TEST_SUITE=flake8
      language: python
      install:
        - pip install flake8
      script:
        - flake8
    - env: TEST_SUITE=nosetests
      sudo: required
      language: python
      python: 2.7
      before_install:
        # provides xmllint used by test_bootstrap_copy (tests.freeze_tests.TestFreeze)
        - sudo apt-get install libxml2-utils
      install:
        # needed to install osc from git in requirements.txt
        - pip install pycurl urlgrabber
        - pip install -r requirements.txt
        - pip install python-coveralls
      script:
        - nosetests --with-coverage --cover-package=osclib --cover-inclusive
      after_success:
        - coveralls

deploy:
  provider: script
  script: ./dist/ci/docker-run obs-deploy
  on:
    branch: master
    condition: $TEST_SUITE = distribution && $TARGET_REPO = openSUSE_Factory

cache:
  directories:
    - .docker-tmp
