language: python
python:
  - 2.7
install:
  - pip install python-coveralls
  # needed to install osc from git in requirements.txt
  - pip install pycurl urlgrabber
  - pip install -r requirements.txt
  - sudo mkdir -p /var/cache/repo-checker
  - sudo chown $USER /var/cache/repo-checker
script:
  - nosetests --with-coverage --cover-package=osclib --cover-inclusive
after_success:
  - coveralls
