format_version: 3
pipelines:
  Pkglistgen.ALP:
    group: LEO
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 10 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - pkglistgen:
        approval:
          type: manual
        jobs:
          SUSE_ALP_target:
            timeout: 60
            resources:
            - repo-checker
            tasks:
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP -s target --only-release-packages --force
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP -s target
          SUSE_ALP_PowerPC:
            timeout: 60
            resources:
            - repo-checker
            tasks:
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:PowerPC -s target --only-release-packages --force
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:PowerPC -s target
          SUSE_ALP_zSystems:
            timeout: 60
            resources:
            - repo-checker
            tasks:
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:zSystems -s target --only-release-packages --force
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:zSystems -s target
          SUSE_ALP_RISCV:
            timeout: 60
            resources:
            - repo-checker
            tasks:
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:RISCV -s target --only-release-packages --force
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:RISCV -s target
          SUSE_ALP_Products_Micro_0.1:
            timeout: 60
            resources:
            - repo-checker
            tasks:
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:Products:Micro:0.1 -s target --only-release-packages --force
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:Products:Micro:0.1 -s target
          SUSE_ALP_Products_Bedrock_0.1:
            timeout: 60
            resources:
            - repo-checker
            tasks:
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:Products:Bedrock:0.1 -s target --only-release-packages --force
            - script: python3 -u ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p SUSE:ALP:Products:Bedrock:0.1 -s target
