format_version: 3
pipelines:
  TTM.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      scripts:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 0 ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot3
        tasks:
        - script: |-
          ./build-fail-reminder.py --sender="DimStar / Dominique Leuenberger <dimstar@opensuse.org>" --project=openSUSE:Factory --relay=relay.suse.de --json=/home/go/config/openSUSE:Factory.reminded.json --debug
