format_version: 3
pipelines:
  openSUSE.Source.Check:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-auto
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot3
            tasks:
            - script: ./check_source.py -A https://api.opensuse.org --verbose --skip-add-reviews --group factory-auto review
  openSUSE.Repochecker:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-repo-checker
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - repo-checker3
            tasks:
            - script: ./repo_checker.py -A https://api.opensuse.org --debug review
  openSUSE.Legal.Check:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-legal-auto
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot3
            tasks:
            - script: ./legal-auto.py -A https://api.opensuse.org --debug --legaldb http://legaldb.suse.de review
  openSUSE.Legal.Import:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 12 ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-legal-auto
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - legal-auto
            tasks:
            - script: ./legal-auto.py -A https://api.opensuse.org --debug --legaldb http://legaldb.suse.de project $(cat /home/go/config/legal-auto-projects-opensuse)
  openSUSE.Maintenance:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */30 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-maintbot
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot3
            tasks:
            - script: ./check_maintenance_incidents.py --verbose review
  Factory.Staging.Report:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
     spec: 0 */3 * ? * *
    environment_variables:
     OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
     git:
       git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
       approval:
         type: manual
       jobs:
         Run:
           timeout: 0
           resources:
           - staging-bot3
           tasks:
           - script: ./staging-report.py --debug -A https://api.opensuse.org -p openSUSE:Factory
  Leap.Staging.Report:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
     spec: 0 */3 * ? * *
    environment_variables:
     OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
     git:
       git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
       approval:
         type: manual
       jobs:
         Run:
           timeout: 0
           resources:
           - staging-bot3
           tasks:
           - script: ./staging-report.py --debug -A https://api.opensuse.org -p openSUSE:Leap:15.1
  Source.In.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
     spec: 0 */30 * ? * *
    environment_variables:
     OSC_CONFIG: /home/go/config/oscrc-factory-source
    materials:
     git:
       git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
       approval:
         type: manual
       jobs:
         Run:
           timeout: 0
           resources:
           - staging-bot3
           tasks:
           - script: ./check_source_in_factory.py --factory openSUSE:Factory --factory openSUSE:Leap:15.0:Update --factory openSUSE:Leap:15.0 --factory openSUSE:Leap:15.0:Update --factory openSUSE:Leap:15.0 --review-mode=fallback-onfail --fallback-group=backports-reviewers --verbose review
