format_version: 3
pipelines:
  openSUSE.Source.Check:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-auto
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 30
            resources:
            - staging-bot
            tasks:
            - script: ./check_source.py -A https://api.opensuse.org --verbose --skip-add-reviews --user factory-auto review
  openSUSE.MaintInstCheck:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-maintenance-installcheck
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 30
            resources:
            - repo-checker
            tasks:
            - script: ./maintenance-installcheck.py -A https://api.opensuse.org --user=maintenance-installcheck --debug review
  openSUSE.Legal.Check:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-legal-auto
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 30
            resources:
            - staging-bot
            tasks:
            - script: ./legal-auto.py -A https://api.opensuse.org --debug --legaldb http://legaldb.suse.de --group=legal-auto review
            - script: ./legal-auto.py -A https://api.opensuse.org --debug --legaldb http://legaldb.suse.de --user=licensedigger review
  openSUSE.Legal.Import:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 12 ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-legal-auto
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 30
            resources:
            - staging-bot
            tasks:
            - script: ./legal-auto.py -A https://api.opensuse.org --debug --legaldb http://legaldb.suse.de project $(cat /home/go/config/legal-auto-projects-opensuse)
  openSUSE.Maintenance:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */30 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-maintbot
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 30
            resources:
            - staging-bot
            tasks:
            - script: ./check_maintenance_incidents.py --verbose review
  openSUSE.Leaper.Maintenance:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 */5 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-leaper
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 30
            resources:
            - staging-bot
            tasks:
            - script: ./leaper.py -A https://api.opensuse.org --verbose project openSUSE:Maintenance maintenance_incident
  Factory.Staging.Report:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
     spec: 0 */3 * ? * *
    environment_variables:
     OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
     git:
       git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
       approval:
         type: manual
       jobs:
         Run:
           timeout: 30
           resources:
           - staging-bot
           tasks:
           - script: ./staging-report.py --debug -A https://api.opensuse.org -p openSUSE:Factory
  Source.In.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
     spec: 0 */30 * ? * *
    environment_variables:
     OSC_CONFIG: /home/go/config/oscrc-factory-source
    materials:
     git:
       git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
       approval:
         type: manual
       jobs:
         Run:
           timeout: 30
           resources:
           - staging-bot
           tasks:
           - script: ./check_source_in_factory.py --factory openSUSE:Factory --factory openSUSE:Leap:15.0:Update --factory openSUSE:Leap:15.0 --factory openSUSE:Leap:15.0:Update --factory openSUSE:Leap:15.0 --review-mode=fallback-onfail --fallback-group=backports-reviewers --verbose review
  Leaper:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-leaper
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 */5 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - staging-bot
        tasks:
          - script: ./leaper.py -A https://api.opensuse.org --verbose --manual-version-updates --manual-maintenance-updates review
  OS.Origin.Manager:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-origin-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 */5 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - staging-bot
        tasks:
          - script: ./origin-manager.py -A https://api.opensuse.org --debug review
  OS.Origin.Manager.Update:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-origin-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 7 ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - staging-bot
        tasks:
          - script: |-
              tempdir=$(mktemp -d)
              mkdir -p $tempdir/.osc-plugins
              ln -s $PWD/osc-origin.py $tempdir/.osc-plugins
              ln -s $PWD/osclib $tempdir/.osc-plugins
              HOME=$tempdir osc -A https://api.opensuse.org origin update
              rm -rf $tempdir
