format_version: 3
pipelines:
  ContainerCleaner.Tumbleweed:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/osc-plugin-factory.git
        branch: master
        destination: scripts
    timer:
      spec: 0 0-23/2 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            scripts/container_cleaner.py --verbose run openSUSE:Containers:Tumbleweed
