format_version: 3
pipelines:
  ContainerCleaner.Tumbleweed:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        branch: master
        destination: scripts
    timer:
      spec: 0 0 0-23/2 ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot-reuse-1
        tasks:
        - script: |-
            export OSRT_DISABLE_CACHE=1
            python3 -u scripts/container_cleaner.py --debug --osc-debug  --http-full-debug --http-debug --verbose run openSUSE:Containers:Tumbleweed
