format_version: 3
pipelines:
  Pkglistgen.openSUSE_Factory:
    group: Factory.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 40 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - pkglistgen:
        approval:
          type: manual
        jobs:
          openSUSE_Factory_target:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Factory -s target
          openSUSE_Factory_rings:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Factory -s rings
          openSUSE_Factory_ARM:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Factory:ARM
          openSUSE_Factory_PowerPC:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Factory:PowerPC
          openSUSE_Factory_zSystems:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Factory:zSystems
  Update.Repos.Factory:
    group: Factory.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 0 21 ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Update:
        approval:
          type: manual
        jobs:
          openSUSE_Factory:
            resources:
            - repo-checker
            tasks:
             - script: python3 ./pkglistgen.py --apiurl https://api.opensuse.org handle_update_repos openSUSE:Factory
          openSUSE_Factory_ARM:
            resources:
            - repo-checker
            tasks:
             - script: python3 ./pkglistgen.py --apiurl https://api.opensuse.org handle_update_repos openSUSE:Factory:ARM
          openSUSE_Factory_PowerPC:
            resources:
            - repo-checker
            tasks:
             - script: python3 ./pkglistgen.py --apiurl https://api.opensuse.org handle_update_repos openSUSE:Factory:PowerPC
  Pkglistgen.openSUSE_Leap:
    group: Leap.15.1.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 10 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - pkglistgen:
        approval:
          type: manual
        jobs:
          openSUSE_Leap_15.1_target:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Leap:15.1 -s target
          openSUSE_Leap_15.1_rings:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Leap:15.1 -s rings
          openSUSE_Leap_15.1_ARM:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Leap:15.1:ARM
          openSUSE_Leap_15.1_PowerPC:
            resources:
            - repo-checker
            tasks:
            - script: python3 ./pkglistgen.py -d -A https://api.opensuse.org update_and_solve -p openSUSE:Leap:15.1:PowerPC
  Update.Repos.Leap:
    group: Leap.15.1.pkglistgen
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    timer:
      spec: 0 0 21 ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Update:
        approval:
          type: manual
        jobs:
          openSUSE_Leap_15.1:
            resources:
            - repo-checker
            tasks:
             - script: python3 ./pkglistgen.py --apiurl https://api.opensuse.org handle_update_repos openSUSE:Leap:15.1
          openSUSE_Leap_15.1_ARM:
            resources:
            - repo-checker
            tasks:
             - script: python3 ./pkglistgen.py --apiurl https://api.opensuse.org handle_update_repos openSUSE:Leap:15.1:ARM
          openSUSE_Leap_15.1_PowerPC:
            resources:
            - repo-checker
            tasks:
             - script: python3 ./pkglistgen.py --apiurl https://api.opensuse.org handle_update_repos openSUSE:Leap:15.1:PowerPC
