format_version: 3
pipelines:
  Trigger.Rebuild.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "openSUSE:Factory"
              ./project-installcheck.py --debug check --store openSUSE:Factory:Staging/dashboard openSUSE:Factory
  Trigger.Rebuild.Factory.Power:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "openSUSE:Factory:PowerPC"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds openSUSE:Factory:PowerPC
  Trigger.Rebuild.Factory.ARM:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "openSUSE:Factory:ARM"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds openSUSE:Factory:ARM
  Trigger.Rebuild.Factory.zSystems:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "openSUSE:Factory:zSystems"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds openSUSE:Factory:zSystems
  Trigger.Rebuild.Factory.RISCV:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "openSUSE:Factory:RISCV"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds openSUSE:Factory:RISCV
  Trigger.Rebuild.GNOME:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "GNOME devel projects"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r openSUSE_Factory GNOME:Factory
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r openSUSE_PPC GNOME:Factory
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r openSUSE_Factory GNOME:Next
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r openSUSE_PPC GNOME:Next
  Trigger.Rebuild.SLE_15_SP4_Backports:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "SLE15 SP4 Backports"
              ./project-installcheck.py --debug check --store openSUSE:Backports:SLE-15-SP4:Staging/dashboard --no-rebuild openSUSE:Backports:SLE-15-SP4
              echo "SLE15 SP4 Step Backports (Rebuilds)"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r step openSUSE:Backports:SLE-15-SP4
  Trigger.Rebuild.Step:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              echo "Step 15-SP4"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r standard openSUSE:Step:15-SP4
              echo "Step 15-SP3"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r standard openSUSE:Step:15-SP3
              echo "Step 15-SP2"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r standard openSUSE:Step:15-SP2
              echo "Step 15-SP1"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r standard openSUSE:Step:15-SP1
              echo "Step 15"
              ./project-installcheck.py --debug check --store home:repo-checker/rebuilds -r standard openSUSE:Step:15
