format_version: 3
pipelines:
  Trigger.Rebuilds:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-factory-maintainer
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
          - repo-checker
        tasks:
          - script: |-
              ln -sf /home/go/config/rebuild.problems problems
              ln -sf /home/go/config/rebuild.buildinfos buildinfos
          - script: |-
              echo "openSUSE:Factory"
              ./rebuildpacs.pl openSUSE:Factory standard i586
              ./rebuildpacs.pl openSUSE:Factory standard x86_64
          - script: |-
              echo "openSUSE:Factory:PowerPC"
              ./rebuildpacs.pl openSUSE:Factory:PowerPC standard ppc
              ./rebuildpacs.pl openSUSE:Factory:PowerPC standard ppc64
              ./rebuildpacs.pl openSUSE:Factory:PowerPC standard ppc64le
          - script: |-
              echo "openSUSE Leap 15.2"
              echo ./rebuildpacs.pl openSUSE:Leap:15.2 standard i586
              echo ./rebuildpacs.pl openSUSE:Leap:15.2 standard x86_64
          - script: |-
              echo "GNOME devel projects"
              ./rebuildpacs.pl GNOME:Factory openSUSE_Factory i586
              ./rebuildpacs.pl GNOME:Factory openSUSE_Factory x86_64
              ./rebuildpacs.pl GNOME:Factory openSUSE_PPC     ppc64le
              ./rebuildpacs.pl GNOME:Next    openSUSE_Factory i586
              ./rebuildpacs.pl GNOME:Next    openSUSE_Factory x86_64
              ./rebuildpacs.pl GNOME:Next    openSUSE_PPC     ppc64le
