format_version: 3
pipelines:
  SLE15.SP2.RelPkgs:
    group: SLE15.SP2.Target
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 10 * ? * *
      only_on_changes: false
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Create.Release.Packages:
        approval: manual
        resources:
        - repo-checker
        tasks:
        - script: ./pkglistgen.py -A https://api.suse.de update_and_solve -p SUSE:SLE-15-SP2:GA -s target --only-release-packages --force

  SLE15.SP2.Package.Lists:
    group: SLE15.SP2.Target
    lock_behavior: unlockWhenFinished
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        destination: repos
        whitelist:
          - SUSE:SLE-15-SP2:GA_-_standard.yaml
      scripts:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        auto_update: true
        destination: scripts
        whitelist:
          - DO_NOT_TRIGGER
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Update.000product:
        resources:
        - repo-checker
        tasks:
        - script: ./scripts/pkglistgen.py -A https://api.suse.de --debug update_and_solve -p SUSE:SLE-15-SP2:GA -s target --force

  SLE15.SP2.Images:
    group: SLE15.SP2.Target
    lock_behavior: unlockWhenFinished
    materials:
      repos:
        git: git://botmaster.suse.de/suse-repos.git
        auto_update: true
        whitelist:
          - SUSE:SLE-15-SP2:GA_-_images.yaml
        destination: repos
      scripts:
        auto_update: true
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        whitelist:
          - DO_NOT_TRIGGER
        destination: scripts
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    stages:
    - Expect.Images.To.Finish:
        resources:
        - staging-bot
        tasks:
        - script: |
            export PYTHONPATH=scripts
            ./scripts/gocd/verify-repo-built-successful.py -A https://api.suse.de -p SUSE:SLE-15-SP2:GA -r images

    - Release.Images.To.Test:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: |-
            for product in kiwi-templates-JeOS \
                SLES15-SP2-BYOS SLES15-SP2-HPC-BYOS \
                SLES15-SP2-SAP SLES15-SP2-SAP-BYOS \
                SLED-15-SP2-Vagrant SLES-15-SP2-Vagrant \
                SLES15-SP2-CHOST-BYOS SLES15-SP2-on-demand \
                SLES15-SP2-Azure SLES15-SP2-Azure-BYOS \
                SLES15-SP2-Azure-Priority SLES15-SP2-Azure-Standard \
                SLES15-SP2-Azure-HPC \
                SLES15-SP2-EC2-ECS-HVM SLES15-SP2-EC2-HVM \
                SLES15-SP2-EC2-HVM-BYOS SLES15-SP2-GCE SLES15-SP2-GCE-BYOS \
                SLES15-SP2-SAP-Azure SLES15-SP2-SAP-Azure-BYOS \
                SLES15-SP2-SAP-Azure-LI-BYOS \
                SLES15-SP2-SAP-Azure-VLI-BYOS \
                SLES15-SP2-SAP-EC2-HVM SLES15-SP2-SAP-EC2-HVM-BYOS \
                SLES15-SP2-OCI-BYOS SLES15-SP2-SAP-OCI-BYOS \
                SLES15-SP2-SAP-GCE SLES15-SP2-SAP-GCE-BYOS 000product; do
              osc -A https://api.suse.de release SUSE:SLE-15-SP2:GA $product
            done

    - Release.Images.To.Publish:
        approval: manual
        roles:
        - SLE
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-totest-manager
        resources:
        - staging-bot
        tasks:
        - script: osc -A https://api.suse.de release SUSE:SLE-15-SP2:GA:TEST
