format_version: 3
pipelines:
  AdiChecker.Factory:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-repo-checker
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
      repos:
        git: git://botmaster.suse.de/opensuse-repos.git
        auto_update: true
        whitelist:
          - openSUSE:Factory:Staging:adi*.yaml
        destination: repos
    stages:
    - Run:
        jobs:
          Run:
            resources:
            - repo-checker
            tasks:
            - script: |-
                ./scripts/staging-installcheck.py -A https://api.opensuse.org -p openSUSE:Factory
  SBot.Regular.Factory:
    group: Factory.pkglistgen
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot
            tasks:
            - script: |-
               set -e
               tempdir=$(mktemp -d)
               mkdir -p $tempdir/.osc-plugins
               ln -s $PWD/osc-staging.py $tempdir/.osc-plugins
               ln -s $PWD/osclib $tempdir/.osc-plugins
               export HOME=$tempdir

               osc -A https://api.opensuse.org staging -p openSUSE:Factory rebuild
               osc -A https://api.opensuse.org staging -p openSUSE:Factory list --supersede
               osc -A https://api.opensuse.org staging -p openSUSE:Factory adi --by-develproject
               osc -A https://api.opensuse.org staging -p openSUSE:Factory select --non-interactive --merge --try-strategies
               osc -A https://api.opensuse.org staging -p openSUSE:Factory unselect --cleanup
               osc -A https://api.opensuse.org staging -p openSUSE:Factory repair --cleanup
               rm -rf $tempdir

  AdiChecker.Leap.15.1:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-repo-checker
    materials:
      script:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
      repos:
        git: git://botmaster.suse.de/opensuse-repos.git
        auto_update: true
        whitelist:
          - openSUSE:Leap:15.1:Staging:adi*.yaml
        destination: repos
    stages:
    - Run:
        jobs:
          Run:
            resources:
            - repo-checker
            tasks:
            - script: |-
                ./scripts/staging-installcheck.py -A https://api.opensuse.org -p openSUSE:Leap:15.1
  SBot.Regular.Leap.15.1:
    group: Leap.15.1.pkglistgen
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 * ? * *
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-staging-bot
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        jobs:
          Run:
            timeout: 0
            resources:
            - staging-bot
            tasks:
            - script: |-
               set -e
               tempdir=$(mktemp -d)
               mkdir -p $tempdir/.osc-plugins
               ln -s $PWD/osc-staging.py $tempdir/.osc-plugins
               ln -s $PWD/osclib $tempdir/.osc-plugins
               export HOME=$tempdir

               osc -A https://api.opensuse.org staging -p openSUSE:Leap:15.1 rebuild
               osc -A https://api.opensuse.org staging -p openSUSE:Leap:15.1 list --supersede
               osc -A https://api.opensuse.org staging -p openSUSE:Leap:15.1 adi --by-develproject
               osc -A https://api.opensuse.org staging -p openSUSE:Leap:15.1 select --non-interactive --merge --try-strategies
               osc -A https://api.opensuse.org staging -p openSUSE:Leap:15.1 unselect --cleanup
               osc -A https://api.opensuse.org staging -p openSUSE:Leap:15.1 repair --cleanup
               rm -rf $tempdir

  Project.Only:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    timer:
      spec: 0 0 * ? * *
      only_on_changes: false
    materials:
      scripts:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
    stages:
    - Run:
        approval:
          type: manual
        environment_variables:
          OSC_CONFIG: /home/go/config/oscrc-repo-checker
        jobs:
          openSUSE.Factory:
            timeout: 0
            resources:
            - repo-checker
            tasks:
            - script: ./project-installcheck.py -A https://api.opensuse.org --debug project_only openSUSE:Factory
          openSUSE.Leap.15.0.Update:
            timeout: 0
            resources:
            - repo-checker
            tasks:
            - script: ./project-installcheck.py -A https://api.opensuse.org --debug project_only openSUSE:Leap:15.0:Update
          openSUSE.Leap.42.3.Update:
            timeout: 0
            resources:
            - repo-checker
            tasks:
            - script: ./project-installcheck.py -A https://api.opensuse.org --debug project_only openSUSE:Leap:42.3:Update
          openSUSE.Leap.15.1.Update:
            timeout: 0
            resources:
            - repo-checker
            tasks:
            - script: ./project-installcheck.py -A https://api.opensuse.org --debug project_only openSUSE:Leap:15.1:Update
