format_version: 3
pipelines:
  openSUSE.Vagrant.Publish:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      ATLAS_TOKEN: '{{SECRET:[opensuse.secrets][ATLAS_TOKEN]}}'
    materials:
      git:
        git: https://github.com/openSUSE/opensuse-release-tools.git
    timer:
      spec: 0 0 0 ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - obs-to-vagrantcloud
        tasks:
        - script: |
            ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/tumbleweed/appliances/boxes/Tumbleweed.x86_64.json --organization opensuse --new-box-name Tumbleweed.x86_64 --provider libvirt
            ruby.ruby3.0 obs-to-vagrantcloud.rb --url https://download.opensuse.org/tumbleweed/appliances/boxes/Tumbleweed.x86_64.json --organization opensuse --new-box-name Tumbleweed.x86_64 --provider virtualbox
