jobs_num: 10
need_same_build_number: true
openqa_group: openSUSE Leap 15 PowerPC
openqa_server: https://openqa.opensuse.org
product_repo: images
products:
  ftp:
  - 000product:openSUSE-ftp-ftp-ppc64le
  main:
  - 000product:openSUSE-cd-mini-ppc64le
  - 000product:openSUSE-dvd5-dvd-ppc64le
take_source_from_product: true
test_subproject: ToTest

