arch: s390x
jobs_num: 1
openqa_group: openSUSE Tumbleweed s390x
openqa_server: https://openqa.opensuse.org
product_repo: images
products:
  ftp:
  - 000product:openSUSE-ftp-ftp-s390x
  main:
  - 000product:openSUSE-dvd5-dvd-s390x
  - 000product:openSUSE-cd-mini-s390x
test_subproject: ToTest

