jobs_num: 70
need_same_build_number: true
openqa_group: openSUSE Leap 15
openqa_server: https://openqa.opensuse.org
product_repo: images
products:
  ftp:
  - 000product:openSUSE-ftp-ftp-x86_64
  - 000product:openSUSE-Addon-NonOss-ftp-ftp-x86_64
  main:
  - 000product:openSUSE-cd-mini-x86_64
  - 000product:openSUSE-dvd5-dvd-x86_64
take_source_from_product: true
test_subproject: ToTest

