jobs_num: 13
openqa_group: openSUSE Leap 15.0 Images
openqa_server: https://openqa.opensuse.org
product_repo: images
products:
  images:
  - livecd-leap-gnome:
    - x86_64
  - livecd-leap-kde:
    - x86_64
  - livecd-leap-x11:
    - x86_64
  - opensuse-leap-image:docker:
    - x86_64
  - opensuse-leap-image:lxc:
    - x86_64
  - kiwi-templates-Leap15-JeOS:MS-HyperV:
    - x86_64
  - kiwi-templates-Leap15-JeOS:OpenStack-Cloud:
    - x86_64
  - kiwi-templates-Leap15-JeOS:VMware:
    - x86_64
  - kiwi-templates-Leap15-JeOS:XEN:
    - x86_64
  - kiwi-templates-Leap15-JeOS:kvm-and-xen:
    - x86_64
set_snapshot_number: true
take_source_from_product: true
test_subproject: ToTest

