arch: ppc64le
jobs_num: 4
openqa_group: openSUSE Tumbleweed PowerPC
openqa_server: https://openqa.opensuse.org
product_repo: images
products:
  container:
  - opensuse-tumbleweed-image:docker:
    - ppc64le
  - kubic-kured-image:
    - ppc64le
  - kubic-pause-image:
    - ppc64le
  ftp:
  - 000product:openSUSE-ftp-ftp-ppc64_ppc64le
  images:
  - opensuse-tumbleweed-image:lxc:
    - ppc64le
  main:
  - 000product:openSUSE-dvd5-dvd-ppc64le
  - 000product:openSUSE-cd-mini-ppc64le
test_subproject: ToTest

