arch: aarch64
jobs_num: 2
openqa_group: openSUSE Tumbleweed AArch64
openqa_server: https://openqa.opensuse.org
product_repo: images
products:
  container:
  - opensuse-tumbleweed-image:docker:
    - aarch64
  - kubic-kured-image:
    - aarch64
  - kubic-pause-image:
    - aarch64
  ftp:
  - 000product:openSUSE-ftp-ftp-aarch64
  - 000product:openSUSE-ftp-ftp-armv7hl
  - 000product:openSUSE-ftp-ftp-armv6hl
  images:
  - opensuse-tumbleweed-image:lxc:
    - armv6l
    - armv7l
    - aarch64
  livecds:
  - JeOS:
    - armv7l
  main:
  - 000product:openSUSE-cd-mini-aarch64
  - 000product:openSUSE-dvd5-dvd-aarch64
  - 000product:openSUSE-Tumbleweed-Kubic-dvd5-dvd-aarch64
test_subproject: ToTest

