name: Checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  tests:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_index: [Long1,Long2,Rest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup path
      run: sed -i -e "s,../..:,$PWD:," dist/ci/docker-compose.yml

    - name: Run tests
      run: docker-compose -f dist/ci/docker-compose.yml run test
      env:
        # Specifies how many jobs you would like to run in parallel,
        # used for partitioning
        CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
        # Use the index from matrix as an environment variable
        CI_NODE_INDEX: ${{ matrix.ci_node_index }}

    - name: Submit coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true

    - name: Stop containers
      if: always()
      run: docker-compose -f dist/ci/docker-compose.yml down

  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Validate gocd config
      run: cd gocd && sh generate.sh && git diff --exit-code

    - name: Setup path
      run: sed -i -e "s,../..:,$PWD:," dist/ci/docker-compose.yml

    - name: Run Flaker
      run: docker-compose -f dist/ci/docker-compose.yml run flaker

    - name: Stop containers
      if: always()
      run: docker-compose -f dist/ci/docker-compose.yml down

