name: tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 40
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup path
      run: sed -i -e "s,../..:,$PWD:," dist/ci/docker-compose.yml

    - name: Run Flaker
      run: docker-compose -f dist/ci/docker-compose.yml run flaker

    - name: Run tests
      run: docker-compose -f dist/ci/docker-compose.yml run test

    - name: Submit coverage report to Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        fail_ci_if_error: true

    - name: Stop containers
      if: always()
      run: docker-compose -f dist/ci/docker-compose.yml down

